dist:     trusty    # используем Ubuntu 14.04 Trusty Tahr (а не 12.02 Precise Pangolin)
sudo:     required  # используем Virtual Machine (а не Docker container)

language: c       # на практике разницы между специфичным для C++ окружением
                    # и, скажем, python -- никакой. Но пусть будет cpp.

os:
  -linux

compiler:
  -gcc
  
script:
    # скрипт сборки и тестирования проекта:
  - cd iz1
  - mkdir build
  - cd build
  - cmake ..
  - make 

after_script:
  - make clean 

