# sudo: false

# dist: xenial

# os: linux

# language: 
# 	- c
# 	- cpp

# before_script:
# 	- cd iz1
# 	- mkdir build
# 	- cd build

# script:
  	# - cmake .. && make
  	# - cd test && ctest

language: c

sudo: false # only for faster builds
script:
  - cd iz1
  - mkdir build
  - cd build
  - cmake .. && make
  - cd test && ctest
