language: cpp
os: linux
dist: xenial
compiler: gcc


before_script:
  - cd iz2
  - mkdir build
  - cd build

jobs: 
  #
  # Valgrind
  #
  - os: linux
    env:
      - TEST="Valgrind"
    addons:
      apt:
        packages:
          - valgrind
    script:
      - cmake ..
      - make
      - ctest -T memcheck

  #
  # CppCheck
  #
  - os: linux
    env:
      - TEST="CppCheck"

    script:
      - cmake -DENABLE_CPPCHECK=ON ..
      - make
      - make check
  
  # 
  # Coverage
  #
  # - os: linux
  #  env:
  #   - TEST="GCovr"
  # addons:
  #   apt:
  #     packages:
  #       - gcov
  # before_script:
  #   - pip3 install gcovr
  # script:
  #   - cmake -DENABLE_GCOV
  #   - make 
  #   - ctest
  #   - cd .. && gcovr 
     
