language: cpp
os: linux
compiler: gcc

sudo: false 

before_scrip:
  - cd iz1
  - mkdir build
  - cd build

matrix: 
  #
  # Valgrind
  #
  - os: linux
    env:
      - TEST="Valgrind"
    addons:
      apt:
        packages:
          - valgrind
    script:
      - cmake ..
      - make
      - ctest -T memcheck

