language: cpp
os: linux
compiler: gcc

sudo: false 

before_scrip:
  - cd iz1
  - mkdir build
  - cd build

matrix: 
  #
  # Valgrind
  #
  - os: linux
    env:
      - TEST="Valgrind"
    addons:
      apt:
        packages:
          - valgrind
    script:
      - cmake ..
      - make
      - ctest -T memcheck

  #
  # CppCheck
  #  
   - os: linux
     env:
       - TEST="CppCheck"
     script:
       - cmake -DENABLE_CPPCHECK=ON -DCMAKE_CXX_COMPILER="g++-6" ..
       - make
       - make check
