language: c

sudo: false # only for faster builds
script:
  - cd iz1
  - mkdir build 
  - cd build
  - cmake .. && make
  - cd test && ctest

after_success:
  - bash <(curl -s https://codecov.io/bash)
